events {
  worker_connections 1024;
}

http {
  upstream coordinator_pool {
    least_conn;
    server coordinator:3000;
  }

  server {
    listen 8080;

    client_max_body_size 128m;

    location / {
      proxy_pass http://coordinator_pool;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}
